# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='users',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='users',
            name='tel',
        ),
        migrations.AddField(
            model_name='users',
            name='create_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='users',
            name='update_time',
            field=models.DateField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterModelTable(
            name='users',
            table='s_user',
        ),
    ]
